# Generated by Django 5.1.4 on 2024-12-19 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traderemark', models.CharField(blank=True, max_length=255, null=True)),
                ('tradebalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tradetype', models.CharField(choices=[('Dining', '餐饮'), ('Transportation', '交通'), ('Shopping', '购物'), ('Entertainment', '娱乐'), ('Education', '教育'), ('Health', '健康'), ('Housing', '住房'), ('Communication', '通讯'), ('Personal Care', '个人护理'), ('Insurance', '保险'), ('Investments', '投资'), ('Gifts', '礼物')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='account.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='budget.budget')),
            ],
        ),
    ]
